"""refactor config to jsonb and add metrics snapshot

Revision ID: 357b6e18989e
Revises: ecc9a267a7a3
Create Date: 2026-03-03 08:14:09.919389+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357b6e18989e'
down_revision: str | None = 'ecc9a267a7a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_snapshots',
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('total_conversations', sa.Integer(), nullable=False),
    sa.Column('messages_sent', sa.Integer(), nullable=False),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=False),
    sa.Column('llm_cost_usd', sa.Float(), nullable=False),
    sa.Column('escalations', sa.Integer(), nullable=False),
    sa.Column('deals_created', sa.Integer(), nullable=False),
    sa.Column('quotes_generated', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('period')
    )
    op.alter_column('system_configs', 'value',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               postgresql_using='value::jsonb')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_configs', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_table('metrics_snapshots')
    # ### end Alembic commands ###
