"""add_wazzup_message_id_index

Revision ID: 2026_02_25_0003
Revises: 2026_02_25_0002
Create Date: 2026-02-25 10:25:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2026_02_25_0003'
down_revision: str | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_messages_wazzup_message_id',
        'messages',
        ['wazzup_message_id'],
        unique=True,
        postgresql_where=sa.text('wazzup_message_id IS NOT NULL')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_messages_wazzup_message_id',
        table_name='messages',
        postgresql_where=sa.text('wazzup_message_id IS NOT NULL')
    )
    # ### end Alembic commands ###
