from __future__ import annotations

from .admin import (
    AdminActionAuditRead,
    AdminActionResult,
    AdminBotRuleApplied,
    AdminBotRulePreviewRequest,
    AdminBotRulePreviewResponse,
    AdminBotRuleRead,
    AdminBotRuleUpdate,
    AdminBotRuleWrite,
    AdminConversationDetail,
    AdminConversationListItem,
    AdminConversationUpdate,
    AdminCustomerListItem,
    AdminEscalationClose,
    AdminEscalationRead,
    AdminEscalationWrite,
    AdminFeedbackRead,
    AdminKnowledgeBaseCandidate,
    AdminKnowledgeBaseCandidateCreate,
    AdminKnowledgeBaseCandidateReject,
    AdminKnowledgeBasePreview,
    AdminKnowledgeBaseRead,
    AdminKnowledgeBaseUpdate,
    AdminKnowledgeBaseWrite,
    AdminManagerReviewSummary,
    AdminOutboundAuditRead,
    AdminQualityReviewSummary,
    AdminResetExecuteRequest,
    AdminResetExecuteResponse,
    AdminResetPreviewRead,
    AdminTimelineMessage,
    ClientSelfTestItem,
    ClientSelfTestStatus,
    ClientSelfTestSubmitRequest,
    ClientSelfTestSubmitResponse,
    DashboardMetricsResponse,
    MetricsResponse,
    NotificationConfigRead,
    NotificationTestResponse,
    PendingManagerReviewRead,
    PromptRead,
    PromptUpdate,
    SalesMetrics,
    SettingsRead,
    SettingsUpdate,
    TimeseriesPoint,
    TimeseriesResponse,
)
from .common import (
    ConversationStatus,
    ErrorResponse,
    EscalationStatus,
    Language,
    PaginatedResponse,
    QualityRating,
    SalesStage,
    TimestampModel,
    UUIDModel,
)
from .conversation import (
    ConversationCreate,
    ConversationDetail,
    ConversationRead,
    ConversationUpdate,
    MessageCreate,
    MessageRead,
)
from .crm import (
    ContactCreate,
    ContactRead,
    DealCreate,
    DealRead,
    DealUpdate,
)
from .health import DependencyHealth, HealthCheckResponse
from .inventory import (
    SaleOrderCreate,
    SaleOrderItem,
    SaleOrderRead,
    StockLevel,
)
from .manager_review import (
    ManagerLeaderboardEntry,
    ManagerReviewDetail,
    ManagerReviewRead,
)
from .product import (
    ProductRead,
    ProductSearchQuery,
    ProductSearchResult,
    ProductSyncRequest,
    ProductSyncResponse,
)
from .quality import (
    QualityCriterion,
    QualityReportRequest,
    QualityReportResponse,
    QualityReviewCreate,
    QualityReviewRead,
)
from .webhook import (
    WazzupIncomingMessage,
    WazzupMedia,
    WazzupWebhookPayload,
)

__all__ = [
    # common
    "ConversationStatus",
    "ErrorResponse",
    "EscalationStatus",
    "Language",
    "PaginatedResponse",
    "QualityRating",
    "SalesStage",
    "TimestampModel",
    "UUIDModel",
    # health
    "DependencyHealth",
    "HealthCheckResponse",
    # webhook
    "WazzupIncomingMessage",
    "WazzupMedia",
    "WazzupWebhookPayload",
    # conversation
    "ConversationCreate",
    "ConversationDetail",
    "ConversationRead",
    "ConversationUpdate",
    "MessageCreate",
    "MessageRead",
    # product
    "ProductRead",
    "ProductSearchQuery",
    "ProductSearchResult",
    "ProductSyncRequest",
    "ProductSyncResponse",
    # crm
    "ContactCreate",
    "ContactRead",
    "DealCreate",
    "DealRead",
    "DealUpdate",
    # inventory
    "SaleOrderCreate",
    "SaleOrderItem",
    "SaleOrderRead",
    "StockLevel",
    # quality
    "QualityCriterion",
    "QualityReportRequest",
    "QualityReportResponse",
    "QualityReviewCreate",
    "QualityReviewRead",
    # admin
    "AdminActionAuditRead",
    "AdminActionResult",
    "AdminBotRuleApplied",
    "AdminBotRulePreviewRequest",
    "AdminBotRulePreviewResponse",
    "AdminBotRuleRead",
    "AdminBotRuleUpdate",
    "AdminBotRuleWrite",
    "AdminConversationDetail",
    "AdminConversationListItem",
    "AdminConversationUpdate",
    "AdminCustomerListItem",
    "AdminEscalationClose",
    "AdminEscalationRead",
    "AdminEscalationWrite",
    "AdminFeedbackRead",
    "AdminKnowledgeBaseCandidate",
    "AdminKnowledgeBaseCandidateCreate",
    "AdminKnowledgeBaseCandidateReject",
    "AdminKnowledgeBasePreview",
    "AdminKnowledgeBaseRead",
    "AdminKnowledgeBaseUpdate",
    "AdminKnowledgeBaseWrite",
    "AdminManagerReviewSummary",
    "AdminOutboundAuditRead",
    "AdminQualityReviewSummary",
    "AdminResetExecuteRequest",
    "AdminResetExecuteResponse",
    "AdminResetPreviewRead",
    "AdminTimelineMessage",
    "ClientSelfTestItem",
    "ClientSelfTestStatus",
    "ClientSelfTestSubmitRequest",
    "ClientSelfTestSubmitResponse",
    "DashboardMetricsResponse",
    "MetricsResponse",
    "NotificationConfigRead",
    "NotificationTestResponse",
    "PendingManagerReviewRead",
    "PromptRead",
    "PromptUpdate",
    "SalesMetrics",
    "SettingsRead",
    "SettingsUpdate",
    "TimeseriesPoint",
    "TimeseriesResponse",
    # manager reviews
    "ManagerLeaderboardEntry",
    "ManagerReviewDetail",
    "ManagerReviewRead",
]
